# Generated by Django 4.2.6 on 2023-10-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ManyToManyField(related_name='articles', to='main.topic'),
        ),
    ]
